# Generated by Django 2.1 on 2018-11-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'запись гостевой книги',
                'verbose_name_plural': 'записи гостевой книги',
                'ordering': ['-posted'],
            },
        ),
    ]
